import type { Metadata } from "next";
import Link from "next/link";
import {
  Activity,
  ArrowLeft,
  Bell,
  LineChart,
  Send,
  ShieldCheck,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Reveal } from "@/components/shared/reveal";
import { SOCIALS } from "@/constants/site";

export const metadata: Metadata = {
  title: "AI Trader Live Signals",
  description:
    "Real-time signals from AI Trader — a real-time algorithmic trading system processing 250+ NSE stocks. Join the Telegram channel for live updates.",
  alternates: { canonical: "/signals" },
};

const SUMMARY = [
  { label: "Stocks tracked", value: "250+", icon: LineChart },
  { label: "Engineered features", value: "56", icon: Activity },
  { label: "Risk-governed", value: "Yes", icon: ShieldCheck },
  { label: "Delivery", value: "Real-time", icon: Bell },
];

export default function SignalsPage() {
  return (
    <div className="container max-w-4xl py-28">
      <Button variant="ghost" size="sm" asChild className="-ml-2 mb-8">
        <Link href="/">
          <ArrowLeft /> Home
        </Link>
      </Button>

      <Reveal>
        <p className="text-sm font-medium text-primary">Live</p>
        <h1 className="mt-2 text-4xl font-bold tracking-tight sm:text-5xl">
          AI Trader Live Signals
        </h1>
        <p className="mt-4 max-w-2xl text-lg text-muted-foreground">
          Real-time signals generated by AI Trader — a real-time algorithmic
          trading system that ingests live market data, generates ML-driven
          signals with calibrated probabilities, and enforces configurable risk
          across 250+ NSE stocks. Signals are published to a public Telegram
          channel.
        </p>
      </Reveal>

      <Reveal delay={0.05}>
        <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">
          {SUMMARY.map(({ label, value, icon: Icon }) => (
            <Card key={label} className="p-5">
              <Icon className="h-5 w-5 text-primary" />
              <p className="mt-3 text-2xl font-semibold">{value}</p>
              <p className="text-xs text-muted-foreground">{label}</p>
            </Card>
          ))}
        </div>
      </Reveal>

      <Reveal delay={0.1}>
        <div className="mt-10 overflow-hidden rounded-2xl border border-border/60 bg-card">
          <div className="relative aspect-[16/8] border-b border-border/60">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,hsl(var(--primary)/0.18),transparent_60%)]" />
            <div className="absolute inset-0 bg-[linear-gradient(to_right,hsl(var(--border))_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--border))_1px,transparent_1px)] bg-[size:32px_32px] opacity-40" />
            <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 text-center">
              <Send className="h-8 w-8 text-primary" />
              <p className="text-sm text-muted-foreground">
                Signal screenshots &amp; dashboard previews coming soon
              </p>
            </div>
          </div>
          <div className="flex flex-col items-center gap-4 p-8 text-center">
            <h2 className="text-2xl font-semibold">Get signals in real time</h2>
            <p className="max-w-md text-sm text-muted-foreground">
              Join the Telegram channel to receive live signals, status updates,
              and performance summaries directly.
            </p>
            <Button size="lg" asChild>
              <Link
                href={SOCIALS.telegram}
                target="_blank"
                rel="noopener noreferrer"
              >
                <Send /> Join Telegram — {SOCIALS.telegramHandle}
              </Link>
            </Button>
          </div>
        </div>
      </Reveal>

      <p className="mt-10 text-center text-xs text-muted-foreground">
        For educational and informational purposes only. Not investment advice.
      </p>
    </div>
  );
}
